server:
  port: 8081

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    api-gateway:
      path: /api/**
      serviceId: api-gateway
      stripPrefix: false
    user-management-service:
      path: /users/**
      serviceId: user-management-service
      stripPrefix: false
    seeker-profile-service:
      path: /seekers/**
      serviceId: seeker-profile-service
      stripPrefix: false
logging:
  file: E:/api-gateway-log.log