server:
  port: 8082
spring:
  application:
    name: seeker-profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/ojp_seeker_profile?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka